name: 'GitHub Issue Parser'
description: 'Turn a GitHub Issues body into a JSON object'
inputs:
  template-path:
    description: 'Path to the issue form template file'
outputs:
  jsonString:
    description: 'JSON string'
runs:
  using: 'node12'
  main: 'dist/index.js'
